(^Д^)

diff --git a/bin/chcs b/bin/chcs
--- a/bin/chcs
+++ b/bin/chcs
@@ -12,24 +12,24 @@ __wsl_env_path() {
 __chcs_wezterm() {
   local dir;
   if is_wsl; then
-    # wezterm must be installed by winget with `--location %APPDATA%/WezTerm`
-    if ! appdata=$(__wsl_env_path APPDATA); then
-      echo 'Failed to get APPDATA'
+    if ! home=$(__wsl_env_path HOMEPATH); then
+      echo 'Failed to get %HOMEPATH%'
       exit 1
     fi
-    dir="$appdata/WezTerm"
+    dir="$home/.config/wezterm"
   else
     dir="$config_home/wezterm"
   fi
+  mkdir -p "$dir"
   if ! [ -d "$dir" ]; then
     echo "$dir is not a directory."
     return 1
   fi
   cat << EOF >| "$dir/_chcs.lua"
-return {
-  window_background_opacity = $2,
-  color_scheme = '$1',
-}
+return function(c)
+  c.window_background_opacity = $2
+  c.color_scheme = '$1'
+end
 EOF
 }
 
diff --git a/env/wsl/wslsync b/env/wsl/wslsync
--- a/env/wsl/wslsync
+++ b/env/wsl/wslsync
@@ -13,13 +13,12 @@ __wsl_env_path() {
 }
 
 __wslsync_wezterm() {
-  # wezterm must be installed via winget with `--location %APPDATA%/WezTerm`
-  if ! appdata=$(__wsl_env_path APPDATA); then
-    echo 'Failed to get APPDATA'
+  if ! home=$(__wsl_env_path HOMEPATH); then
+    echo 'Failed to get %HOMEPATH%'
     exit 1
   fi
   d="$config_home/wezterm/wezterm.lua"
-  w="$appdata/WezTerm/wezterm.lua"
+  w="$home/.config/wezterm/wezterm.lua"
   __wslsync_do
 }
 
